#!/bin/bash
#PBS -N Signal
#PBS -l nodes=1
#PBS -o Signal_OUTPUT.txt
#PBS -e Signal_ERROR.txt
#PBS -M camilo@gfif.udea.edu.co

#ROOT PATH (Uncoment the version you want)
#Root 5
source /opt/root/bin/thisroot.sh
#Root 6
#source /opt/root-curso/bin/thisroot.sh

#MadGraph
export MadGrapgSYS=/scratch/cms/MadGraph/MG5_aMC_v2_5_2
export PATH=$PATH:$MadGrapgSYS/bin

cd $PBS_O_WORKDIR
#Single Top
./produccion-1.sh BackGround-tW.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/pythia8_card.dat
#WJets

./produccion-1.sh BackGround-llW.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/pythia8_card.dat

./produccion-1.sh BackGround-mumuW.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/pythia8_card.dat

./produccion-1.sh BackGround-tautauW.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/Wjet/pythia8_card.dat

#Single Top
./produccion-1.sh BackGround-SingleTop.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/SingleTop/pythia8_card.dat

#WW
./produccion-1.sh BackGround-WW.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WW/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WW/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WW/pythia8_card.dat

#WZ
./produccion-1.sh BackGround-WZ.txt -Ne=10000 -Run=2 -Rc=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WZ/run_card.dat -Delp=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WZ/delphes_card.dat -Pyt=/home/camilo/cms/Scripts_MadGraph_VLFTEO/Cards_Costumed/WZ/pythia8_card.dat
